{{- if and  .Values.serviceAccount.create .Values.clusterRole.create}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusteRoleBinding.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name}}
  namespace: {{ .Values.serviceAccount.namespace }}
{{- end}}
