apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name}}
  namespace: {{ .Values.configMap.namespace}}
data:
  fluent.conf: |-
{{ .Files.Get "fluentd-config/fluent.conf"| indent 4 }}
  pods-fluent.conf: |-
{{ tpl (.Files.Get "fluentd-config/pods-fluent.conf") .| indent 4 }}