{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name}}
  namespace: {{ .Values.serviceAccount.namespace }}
  labels: {{- include "fluentd.common.labels" . | nindent 4 }}
{{- end }}