apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Values.fluentd.namespace }}
  labels: {{- include "fluentd.common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "fluentd.common.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "fluentd.common.labels" . | nindent 8 }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccount: {{ .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        imagePullPolicy: {{ .Values.fluentd.imagePullPolicy | quote}}
        image: {{ .Values.fluentd.image }}
        #image:  fluent/fluentd-kubernetes-daemonset:v1.14.0-debian-forward-amd64-1.1
        #env:
        #  - name: FLUENT_KAFKA_BROKERS
        #    value: "192.168.2.239:9092"
        #  - name: FLUENT_UID
        #    value: '9000'
        #  - name: FLUENTD_SYSTEMD_CONF
        #    value: 'disable'
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-config
        configMap:
          name: {{ .Values.configMap.name}}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
